# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirige la raíz a tu basePath
[[redirects]]
  from = "/"
  to = "/turtle-conservation-app"
  status = 301
